### ISSUE TITLE
scroll problem 

### ISSUE THREAD

**Issue by sabeerbikba** [Jlopez2045/vsc-phind#1]
some times can't scroll when generating result check in video 
https://github.com/Jlopez2045/vsc-phind/assets/59386700/a7655d21-1cc2-4f09-8dc1-7de56b7000d5

**Comment by Jlopez2045** [comment]
Sorry this is not the official extension, it has been deprecated. In the video you are using the official.

**Comment by sabeerbikba** [comment]
I clicked the link that redirected me to this repository

**Comment by sabeerbikba** [comment]
I clicked the link that redirected me to this repository. Can you provide me official repository link?
